/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define SOPT4_TPM1CH0SRC_TPM1_CH0 0x00u /*!<@brief TPM1 channel 0 input capture source select: TPM1_CH0 signal */
#define SOPT4_TPM2CH0SRC_TPM2_CH0 0x00u /*!<@brief TPM2 channel 0 input capture source select: TPM2_CH0 signal */
#define SOPT5_UART0RXSRC_UART_RX 0x00u  /*!<@brief UART0 receive data source select: UART0_RX pin */
#define SOPT5_UART0TXSRC_UART_TX 0x00u  /*!<@brief UART0 transmit data source select: UART0_TX pin */
#define SOPT5_UART1RXSRC_UART_RX 0x00u  /*!<@brief UART1 receive data source select: UART1_RX pin */
#define SOPT5_UART1TXSRC_UART_TX 0x00u  /*!<@brief UART1 transmit data source select: UART1_TX pin */

/*! @name PORTA12 (number 32), J1[8]/D3
  @{ */
#define BOARD_INITPINS_STEERING_PORT PORTA /*!<@brief PORT device name: PORTA */
#define BOARD_INITPINS_STEERING_PIN 12U    /*!<@brief PORTA pin index: 12 */
                                           /* @} */

/*! @name PORTD5 (number 78), J2[4]/D9
  @{ */
#define BOARD_INITPINS_MOTOR_PWM_G_1_PORT PORTD /*!<@brief PORT device name: PORTD */
#define BOARD_INITPINS_MOTOR_PWM_G_1_PIN 5U     /*!<@brief PORTD pin index: 5 */
                                                /* @} */

/*! @name PORTD0 (number 73), J2[6]/D10
  @{ */
#define BOARD_INITPINS_MOTOR_PWM_G_2_PORT PORTD /*!<@brief PORT device name: PORTD */
#define BOARD_INITPINS_MOTOR_PWM_G_2_PIN 0U     /*!<@brief PORTD pin index: 0 */
                                                /* @} */

/*! @name PORTD2 (number 75), J2[8]/D11
  @{ */
#define BOARD_INITPINS_MOTOR_PWM_D_1_PORT PORTD /*!<@brief PORT device name: PORTD */
#define BOARD_INITPINS_MOTOR_PWM_D_1_PIN 2U     /*!<@brief PORTD pin index: 2 */
                                                /* @} */

/*! @name PORTD3 (number 76), J2[10]/D12
  @{ */
#define BOARD_INITPINS_MOTOR_PWM_D_2_PORT PORTD /*!<@brief PORT device name: PORTD */
#define BOARD_INITPINS_MOTOR_PWM_D_2_PIN 3U     /*!<@brief PORTD pin index: 3 */
                                                /* @} */

/*! @name PORTE22 (number 15), J10[5]
  @{ */
#define BOARD_INITPINS_SPEED_1_PORT PORTE /*!<@brief PORT device name: PORTE */
#define BOARD_INITPINS_SPEED_1_PIN 22U    /*!<@brief PORTE pin index: 22 */
                                          /* @} */

/*! @name PORTB18 (number 53), D3[1]/LEDRGB_RED
  @{ */
#define BOARD_INITPINS_LED_RED_GPIO GPIOB /*!<@brief GPIO device name: GPIOB */
#define BOARD_INITPINS_LED_RED_PORT PORTB /*!<@brief PORT device name: PORTB */
#define BOARD_INITPINS_LED_RED_PIN 18U    /*!<@brief PORTB pin index: 18 */
                                          /* @} */

/*! @name PORTB19 (number 54), D3[4]/LEDRGB_GREEN
  @{ */
#define BOARD_INITPINS_LED_GREEN_GPIO GPIOB /*!<@brief GPIO device name: GPIOB */
#define BOARD_INITPINS_LED_GREEN_PORT PORTB /*!<@brief PORT device name: PORTB */
#define BOARD_INITPINS_LED_GREEN_PIN 19U    /*!<@brief PORTB pin index: 19 */
                                            /* @} */

/*! @name PORTD1 (number 74), J2[12]/D3[3]/D13/LEDRGB_BLUE
  @{ */
#define BOARD_INITPINS_LED_BLUE_GPIO GPIOD /*!<@brief GPIO device name: GPIOD */
#define BOARD_INITPINS_LED_BLUE_PORT PORTD /*!<@brief PORT device name: PORTD */
#define BOARD_INITPINS_LED_BLUE_PIN 1U     /*!<@brief PORTD pin index: 1 */
                                           /* @} */

/*! @name PORTB11 (number 50), J9[7]
  @{ */
#define BOARD_INITPINS_CCD_SI_0_GPIO GPIOB /*!<@brief GPIO device name: GPIOB */
#define BOARD_INITPINS_CCD_SI_0_PORT PORTB /*!<@brief PORT device name: PORTB */
#define BOARD_INITPINS_CCD_SI_0_PIN 11U    /*!<@brief PORTB pin index: 11 */
                                           /* @} */

/*! @name PORTB10 (number 49), J9[5]
  @{ */
#define BOARD_INITPINS_CCD_CLK_0_GPIO GPIOB /*!<@brief GPIO device name: GPIOB */
#define BOARD_INITPINS_CCD_CLK_0_PORT PORTB /*!<@brief PORT device name: PORTB */
#define BOARD_INITPINS_CCD_CLK_0_PIN 10U    /*!<@brief PORTB pin index: 10 */
                                            /* @} */

/*! @name PORTC2 (number 57), J10[10]/A4
  @{ */
#define BOARD_INITPINS_CCD_AD_0_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_INITPINS_CCD_AD_0_PIN 2U     /*!<@brief PORTC pin index: 2 */
                                           /* @} */

/*! @name PORTE23 (number 16), J10[7]
  @{ */
#define BOARD_INITPINS_SPEED_2_PORT PORTE /*!<@brief PORT device name: PORTE */
#define BOARD_INITPINS_SPEED_2_PIN 23U    /*!<@brief PORTE pin index: 23 */
                                          /* @} */

/*! @name PORTE0 (number 1), J2[18]/D14
  @{ */
#define BOARD_INITPINS_BLUETOOTH_TX_PORT PORTE /*!<@brief PORT device name: PORTE */
#define BOARD_INITPINS_BLUETOOTH_TX_PIN 0U     /*!<@brief PORTE pin index: 0 */
                                               /* @} */

/*! @name PORTE1 (number 2), J2[20]/D15
  @{ */
#define BOARD_INITPINS_BLUETOOTH_RX_PORT PORTE /*!<@brief PORT device name: PORTE */
#define BOARD_INITPINS_BLUETOOTH_RX_PIN 1U     /*!<@brief PORTE pin index: 1 */
                                               /* @} */

/*! @name PORTC1 (number 56), J10[12]/U6[31]/A5
  @{ */
#define BOARD_INITPINS_CCD_AD_1_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_INITPINS_CCD_AD_1_PIN 1U     /*!<@brief PORTC pin index: 1 */
                                           /* @} */

/*! @name PORTB9 (number 48), J9[3]
  @{ */
#define BOARD_INITPINS_CCD_CLK_1_GPIO GPIOB /*!<@brief GPIO device name: GPIOB */
#define BOARD_INITPINS_CCD_CLK_1_PORT PORTB /*!<@brief PORT device name: PORTB */
#define BOARD_INITPINS_CCD_CLK_1_PIN 9U     /*!<@brief PORTB pin index: 9 */
                                            /* @} */

/*! @name PORTB8 (number 47), J9[1]
  @{ */
#define BOARD_INITPINS_CCD_SI_1_GPIO GPIOB /*!<@brief GPIO device name: GPIOB */
#define BOARD_INITPINS_CCD_SI_1_PORT PORTB /*!<@brief PORT device name: PORTB */
#define BOARD_INITPINS_CCD_SI_1_PIN 8U     /*!<@brief PORTB pin index: 8 */
                                           /* @} */

/*! @name PORTE30 (number 22), J10[11]
  @{ */
#define BOARD_INITPINS_FB_G_1_PORT PORTE /*!<@brief PORT device name: PORTE */
#define BOARD_INITPINS_FB_G_1_PIN 30U    /*!<@brief PORTE pin index: 30 */
                                         /* @} */

/*! @name PORTE29 (number 21), J10[9]
  @{ */
#define BOARD_INITPINS_FB_G_2_PORT PORTE /*!<@brief PORT device name: PORTE */
#define BOARD_INITPINS_FB_G_2_PIN 29U    /*!<@brief PORTE pin index: 29 */
                                         /* @} */

/*! @name PORTE20 (number 13), J10[1]
  @{ */
#define BOARD_INITPINS_FB_D_1_PORT PORTE /*!<@brief PORT device name: PORTE */
#define BOARD_INITPINS_FB_D_1_PIN 20U    /*!<@brief PORTE pin index: 20 */
                                         /* @} */

/*! @name PORTB0 (number 43), J10[2]/A0
  @{ */
#define BOARD_INITPINS_FB_D_2_PORT PORTB /*!<@brief PORT device name: PORTB */
#define BOARD_INITPINS_FB_D_2_PIN 0U     /*!<@brief PORTB pin index: 0 */
                                         /* @} */

/*! @name PORTB3 (number 46), J10[8]/A3
  @{ */
#define BOARD_INITPINS_POT_1_PORT PORTB /*!<@brief PORT device name: PORTB */
#define BOARD_INITPINS_POT_1_PIN 3U     /*!<@brief PORTB pin index: 3 */
                                        /* @} */

/*! @name PORTB2 (number 45), J10[6]/A2
  @{ */
#define BOARD_INITPINS_POT_2_PORT PORTB /*!<@brief PORT device name: PORTB */
#define BOARD_INITPINS_POT_2_PIN 2U     /*!<@brief PORTB pin index: 2 */
                                        /* @} */

/*! @name PORTB1 (number 44), J10[4]/A1
  @{ */
#define BOARD_INITPINS_POT_3_PORT PORTB /*!<@brief PORT device name: PORTB */
#define BOARD_INITPINS_POT_3_PIN 1U     /*!<@brief PORTB pin index: 1 */
                                        /* @} */

/*! @name PORTC8 (number 65), J1[14]
  @{ */
#define BOARD_INITPINS_AGM_I2C_SCL_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_INITPINS_AGM_I2C_SCL_PIN 8U     /*!<@brief PORTC pin index: 8 */
                                              /* @} */

/*! @name PORTC9 (number 66), J1[16]
  @{ */
#define BOARD_INITPINS_AGM_I2C_SDA_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_INITPINS_AGM_I2C_SDA_PIN 9U     /*!<@brief PORTC pin index: 9 */
                                              /* @} */

/*! @name PORTE3 (number 4), J9[11]
  @{ */
#define BOARD_INITPINS_ACC_INT_1_GPIO GPIOE /*!<@brief GPIO device name: GPIOE */
#define BOARD_INITPINS_ACC_INT_1_PORT PORTE /*!<@brief PORT device name: PORTE */
#define BOARD_INITPINS_ACC_INT_1_PIN 3U     /*!<@brief PORTE pin index: 3 */
                                            /* @} */

/*! @name PORTE2 (number 3), J9[9]
  @{ */
#define BOARD_INITPINS_ACC_INT_2_GPIO GPIOE /*!<@brief GPIO device name: GPIOE */
#define BOARD_INITPINS_ACC_INT_2_PORT PORTE /*!<@brief PORT device name: PORTE */
#define BOARD_INITPINS_ACC_INT_2_PIN 2U     /*!<@brief PORTE pin index: 2 */
                                            /* @} */

/*! @name PORTE5 (number 6), J9[15]
  @{ */
#define BOARD_INITPINS_GYR_INT_1_GPIO GPIOE /*!<@brief GPIO device name: GPIOE */
#define BOARD_INITPINS_GYR_INT_1_PORT PORTE /*!<@brief PORT device name: PORTE */
#define BOARD_INITPINS_GYR_INT_1_PIN 5U     /*!<@brief PORTE pin index: 5 */
                                            /* @} */

/*! @name PORTE4 (number 5), J9[13]
  @{ */
#define BOARD_INITPINS_GYR_INT_2_GPIO GPIOE /*!<@brief GPIO device name: GPIOE */
#define BOARD_INITPINS_GYR_INT_2_PORT PORTE /*!<@brief PORT device name: PORTE */
#define BOARD_INITPINS_GYR_INT_2_PIN 4U     /*!<@brief PORTE pin index: 4 */
                                            /* @} */

/*! @name PORTC17 (number 72), J2[7]
  @{ */
#define BOARD_INITPINS_MAG_INT_GPIO GPIOC /*!<@brief GPIO device name: GPIOC */
#define BOARD_INITPINS_MAG_INT_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_INITPINS_MAG_INT_PIN 17U    /*!<@brief PORTC pin index: 17 */
                                          /* @} */

/*! @name PORTA16 (number 36), J2[9]
  @{ */
#define BOARD_INITPINS_MAG_DRDY_GPIO GPIOA /*!<@brief GPIO device name: GPIOA */
#define BOARD_INITPINS_MAG_DRDY_PORT PORTA /*!<@brief PORT device name: PORTA */
#define BOARD_INITPINS_MAG_DRDY_PIN 16U    /*!<@brief PORTA pin index: 16 */
                                           /* @} */

/*! @name PORTC7 (number 64), J1[1]
  @{ */
#define BOARD_INITPINS_LED_6_GPIO GPIOC /*!<@brief GPIO device name: GPIOC */
#define BOARD_INITPINS_LED_6_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_INITPINS_LED_6_PIN 7U     /*!<@brief PORTC pin index: 7 */
                                        /* @} */

/*! @name PORTC0 (number 55), J1[3]
  @{ */
#define BOARD_INITPINS_LED_5_GPIO GPIOC /*!<@brief GPIO device name: GPIOC */
#define BOARD_INITPINS_LED_5_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_INITPINS_LED_5_PIN 0U     /*!<@brief PORTC pin index: 0 */
                                        /* @} */

/*! @name PORTC3 (number 58), J1[5]
  @{ */
#define BOARD_INITPINS_LED_4_GPIO GPIOC /*!<@brief GPIO device name: GPIOC */
#define BOARD_INITPINS_LED_4_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_INITPINS_LED_4_PIN 3U     /*!<@brief PORTC pin index: 3 */
                                        /* @} */

/*! @name PORTC4 (number 61), J1[7]
  @{ */
#define BOARD_INITPINS_LED_3_GPIO GPIOC /*!<@brief GPIO device name: GPIOC */
#define BOARD_INITPINS_LED_3_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_INITPINS_LED_3_PIN 4U     /*!<@brief PORTC pin index: 4 */
                                        /* @} */

/*! @name PORTC5 (number 62), J1[9]
  @{ */
#define BOARD_INITPINS_LED_2_GPIO GPIOC /*!<@brief GPIO device name: GPIOC */
#define BOARD_INITPINS_LED_2_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_INITPINS_LED_2_PIN 5U     /*!<@brief PORTC pin index: 5 */
                                        /* @} */

/*! @name PORTC6 (number 63), J1[11]
  @{ */
#define BOARD_INITPINS_LED_1_GPIO GPIOC /*!<@brief GPIO device name: GPIOC */
#define BOARD_INITPINS_LED_1_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_INITPINS_LED_1_PIN 6U     /*!<@brief PORTC pin index: 6 */
                                        /* @} */

/*! @name PORTC12 (number 69), J2[1]
  @{ */
#define BOARD_INITPINS_SW_1_GPIO GPIOC /*!<@brief GPIO device name: GPIOC */
#define BOARD_INITPINS_SW_1_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_INITPINS_SW_1_PIN 12U    /*!<@brief PORTC pin index: 12 */
                                       /* @} */

/*! @name PORTC13 (number 70), J2[3]
  @{ */
#define BOARD_INITPINS_SW_2_GPIO GPIOC /*!<@brief GPIO device name: GPIOC */
#define BOARD_INITPINS_SW_2_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_INITPINS_SW_2_PIN 13U    /*!<@brief PORTC pin index: 13 */
                                       /* @} */

/*! @name PORTC16 (number 71), J2[5]
  @{ */
#define BOARD_INITPINS_SW_3_GPIO GPIOC /*!<@brief GPIO device name: GPIOC */
#define BOARD_INITPINS_SW_3_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_INITPINS_SW_3_PIN 16U    /*!<@brief PORTC pin index: 16 */
                                       /* @} */

/*! @name PORTC11 (number 68), J1[15]
  @{ */
#define BOARD_INITPINS_SW_4_GPIO GPIOC /*!<@brief GPIO device name: GPIOC */
#define BOARD_INITPINS_SW_4_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_INITPINS_SW_4_PIN 11U    /*!<@brief PORTC pin index: 11 */
                                       /* @} */

/*! @name PORTC10 (number 67), J1[13]
  @{ */
#define BOARD_INITPINS_SW_5_GPIO GPIOC /*!<@brief GPIO device name: GPIOC */
#define BOARD_INITPINS_SW_5_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_INITPINS_SW_5_PIN 10U    /*!<@brief PORTC pin index: 10 */
                                       /* @} */

/*! @name PORTA5 (number 31), J1[12]/D5
  @{ */
#define BOARD_INITPINS_SW_6_GPIO GPIOA /*!<@brief GPIO device name: GPIOA */
#define BOARD_INITPINS_SW_6_PORT PORTA /*!<@brief PORT device name: PORTA */
#define BOARD_INITPINS_SW_6_PIN 5U     /*!<@brief PORTA pin index: 5 */
                                       /* @} */

/*! @name PORTA4 (number 30), J1[10]/D4
  @{ */
#define BOARD_INITPINS_SW_7_GPIO GPIOA /*!<@brief GPIO device name: GPIOA */
#define BOARD_INITPINS_SW_7_PORT PORTA /*!<@brief PORT device name: PORTA */
#define BOARD_INITPINS_SW_7_PIN 4U     /*!<@brief PORTA pin index: 4 */
                                       /* @} */

/*! @name PORTD4 (number 77), J1[6]/D2
  @{ */
#define BOARD_INITPINS_SW_8_GPIO GPIOD /*!<@brief GPIO device name: GPIOD */
#define BOARD_INITPINS_SW_8_PORT PORTD /*!<@brief PORT device name: PORTD */
#define BOARD_INITPINS_SW_8_PIN 4U     /*!<@brief PORTD pin index: 4 */
                                       /* @} */

/*! @name PORTA2 (number 28), J1[4]/D1/UART0_TX
  @{ */
#define BOARD_INITPINS_DEBUG_UART_TX_PORT PORTA /*!<@brief PORT device name: PORTA */
#define BOARD_INITPINS_DEBUG_UART_TX_PIN 2U     /*!<@brief PORTA pin index: 2 */
                                                /* @} */

/*! @name PORTA1 (number 27), J1[2]/D0/UART0_RX
  @{ */
#define BOARD_INITPINS_DEBUG_UART_RX_PORT PORTA /*!<@brief PORT device name: PORTA */
#define BOARD_INITPINS_DEBUG_UART_RX_PIN 1U     /*!<@brief PORTA pin index: 1 */
                                                /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

/*! @name PORTC8 (number 65), J1[14]
  @{ */
#define BOARD_I2C_CONFIGUREPINS_AGM_I2C_SCL_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_I2C_CONFIGUREPINS_AGM_I2C_SCL_PIN 8U     /*!<@brief PORTC pin index: 8 */
                                                       /* @} */

/*! @name PORTC9 (number 66), J1[16]
  @{ */
#define BOARD_I2C_CONFIGUREPINS_AGM_I2C_SDA_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_I2C_CONFIGUREPINS_AGM_I2C_SDA_PIN 9U     /*!<@brief PORTC pin index: 9 */
                                                       /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_I2C_ConfigurePins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
